// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {service} from '../models';

export function InsertCollection(arg1:string):Promise<types.Response>;

export function QueryCollections():Promise<Array<service.ConnCollection>>;

export function QueryConnInfos(arg1:number):Promise<Array<service.ConnInfo>>;
