// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InsertCollection(arg1) {
  return window['go']['service']['CollectionService']['InsertCollection'](arg1);
}

export function QueryCollections() {
  return window['go']['service']['CollectionService']['QueryCollections']();
}

export function QueryConnInfos(arg1) {
  return window['go']['service']['CollectionService']['QueryConnInfos'](arg1);
}
