// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCollection(arg1) {
  return window['go']['service']['CollectionService']['DeleteCollection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['service']['CollectionService']['DeleteConnection'](arg1);
}

export function InsertCollection(arg1) {
  return window['go']['service']['CollectionService']['InsertCollection'](arg1);
}

export function InsertConnection(arg1) {
  return window['go']['service']['CollectionService']['InsertConnection'](arg1);
}

export function QueryAllConnectionRel() {
  return window['go']['service']['CollectionService']['QueryAllConnectionRel']();
}
