// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TestConnection(arg1) {
  return window['go']['service']['ShellService']['TestConnection'](arg1);
}
